### ISSUE TITLE
Problem in Rmarkdown inline rendering with dark-themed Rstudio

### ISSUE THREAD

**Issue by arthurwelle** [glin/reactable#21] opened 2019-12-13 14:12 UTC
Hi, nice work on the package! 
I´m using Rstudio with a dark theme ("vibrant ink"), and the tables shown in the preview of the Rmakdown are blank due to its font color.  
Regards!

![image](https://user-images.githubusercontent.com/6665804/70805942-e906e880-1d98-11ea-87d8-f04af68617cd.png)

**Comment by glin** [comment] 2020-03-22 20:38
Hi, thanks for reporting this, and sorry it took a while to respond. This should now be fixed in the latest development version on GitHub (https://github.com/glin/reactable/commit/670de5bd850c67f685418f44f08565dce5cdbdb1).

The problem is that the IDE applies the dark theme's text color styles to HTML widget output in R Notebooks. Since reactable doesn't set a default text color on most parts of the table, you end up with light text on white background. This seems to only happen with htmltools 0.4.0 installed, not 0.3.6 or older, so I think it's more of an issue with the IDE or htmltools. However, I've still implemented a workaround by setting an explicit text color on the table when rendered in an R Notebook.

![image](https://user-images.githubusercontent.com/20401866/77259533-17c21400-6c50-11ea-8df2-14c89fe9b4e3.png)

**Closed by glin** 2020-03-22 20:38 UTC
