### ISSUE TITLE
Floating footer when pagination is false

### ISSUE THREAD

**Issue by Kairi703** [glin/reactable#41] opened 2020-04-14 10:10 UTC
Hi All,

Thanks for creating an amazing package, which helps with the huge reports I have to create right now.

When I use both footer and pagination = FALSE with a set height, the footer kinda floats on top of the table. 

Example: 

reactable(
  iris[,-5],
  defaultColDef = colDef(footer = function(values) sum(values)
                         ),
  wrap = TRUE,
  pagination = FALSE, 
  highlight = TRUE, 
  height = 500,
  columns = list(
    Sepal.Length = colDef(name = "Sepal Length"),
    Sepal.Width = colDef(filterable = TRUE),
    Petal.Length = colDef(show = FALSE),
    Petal.Width = colDef(defaultSortOrder = "desc")
  )
)

**Comment by glin** [comment] 2020-04-18 16:06
Thanks for reporting this. I've seen this before in either Safari or the RStudio Viewer, but I forgot to go back and investigate it. I think it's a browser bug with sticky elements. What browser are you using?

**Comment by Kairi703** [comment] 2020-04-18 18:40
Thanks for the reply. I checked, and the behavior only occurs in the Rstudio viewer, not in Edge or Chrome. I don't know about safari, as I don't use a Mac :) That makes it less of a worry for me, as my client does not use Rstudio viewer to check the html.

**Comment by glin** [comment] 2020-05-28 02:09
I finally looked into this and found that it was caused by a flexbox bug in several browsers, including Safari and Chrome: https://github.com/philipwalton/flexbugs#flexbug-1.

The bug is supposed to be fixed in newer versions of Chrome and Safari, but I added a workaround for it anyway in https://github.com/glin/reactable/commit/2bfeb409bb852f73beace79b0b2099c013521061. So footers should no longer be floating for Chrome, Safari, and the RStudio Viewer.

**Closed by glin** 2020-05-28 02:09 UTC
