### ISSUE TITLE
Collapsed row height with no pagination

### ISSUE THREAD

**Issue by ajirnyi** [glin/reactable#69] opened 2020-08-20 15:58 UTC
In the Shiny demo (as well as in my code), when Pagination is disabled, and Grouping by Species is enabled, the collapsed rows have very large height. Is there any workaround for this?

**Comment by glin** [comment] 2020-08-23 19:52
Hi, thanks for the report. This is now fixed in the development version (https://github.com/glin/reactable/commit/d53a2ba308bf5e6900757290d5c4245e54257ca9). 

The issue was that before, the table rows would stretch to fill the vertical space if there was more space than necessary. This was awkward if the table had a fixed height, but not enough rows to fill out that height:
```r
reactable(
  MASS::Cars93[1:4, 1:4],
  defaultColDef = colDef(footer = "footer"),
  height = 300,
  outlined = TRUE
)
```
![reactable with stretched rows](https://user-images.githubusercontent.com/20401866/90987147-5d13a600-e54e-11ea-8245-5ca89447f168.png)


Now, the table rows won't stretch, which looks less awkward in most cases:
![reactable without stretched rows](https://user-images.githubusercontent.com/20401866/90987306-8b45b580-e54f-11ea-9e8e-0cfaf11a3267.png)

I think the row stretching was originally intended behavior, so here's a way to restore that if necessary. Use a theme like `reactableTheme(tableBodyStyle = list(flex = "auto"))`:

```r
reactable(
  MASS::Cars93[1:4, 1:4],
  defaultColDef = colDef(footer = "footer"),
  height = 300,
  outlined = TRUE,
  theme = reactableTheme(tableBodyStyle = list(flex = "auto"))
)
```

**Closed by glin** 2020-08-23 19:52 UTC
